### test 1
POST http://127.0.0.1:5005/upload-ig
Content-Type: application/json

{"serverBase": "https://fhir.hl7.pt/r4/fhir",
    "packageId" : "hl7.fhir.eu.laboratory"}

#    packagebase64 = data["packagebase64"]
#  "usePUT" : true,
#    "loadRecursively" : true,
